name:                compiler-bootstrap
version:             0.1.0.0
github:              "tao-language/compiler-bootstrap"
license:             MIT
author:              "David Cavazos"
maintainer:          "dcavazosw@gmail.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tao-language/compiler-bootstrap#README.md>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- process
- sort
- split

library:
  source-dirs: src

ghc-options:
  # TODO: re-enable warnings
  - -w
  # - -Wall
  # - -Wno-name-shadowing
  - -j8
  - -XDuplicateRecordFields
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XInstanceSigs
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XNoFieldSelectors
  - -XOverloadedRecordDot
  - -XTupleSections
  - -XTypeSynonymInstances

executables:
  tao-bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j8
    dependencies:
    - compiler-bootstrap

tests:
  tao-bootstrap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compiler-bootstrap
    - hspec
