name: Î»

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          # Best effort for cache: tie it to Stack resolver and package config
          key: ubuntu-latest-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ubuntu-latest-stack

      - run: stack build --ghc-options="-Werror"

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - uses: actions/setup-python@v5

      - uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          # Best effort for cache: tie it to Stack resolver and package config
          key: ${{ matrix.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-stack

      - run: stack test
