name: Î»

on: push

env:
  GHC_VERSION: '9.8.2'

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: haskell-actions/setup@v2
  #       with:
  #         ghc-version: ${{ env.GHC_VERSION }}
  #         enable-stack: true

  #     - run: stack build --ghc-options="-Werror"

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          enable-stack: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: stack build --test --no-run-tests
      - run: stack test
